# Generated by Django 3.2.3 on 2021-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alertId', models.CharField(help_text='A unique alert record ID', max_length=20, primary_key=True, serialize=False)),
                ('alertRule', models.CharField(help_text='Name of the alert rule that fired', max_length=20)),
                ('confidence', models.IntegerField(default=0, help_text='Confidence score given to the alert that fired', max_length=20)),
                ('firedDateTime', models.DateTimeField(help_text='Date Time that the alert was triggered')),
                ('sentDateTime', models.DateTimeField(auto_now=True, help_text='Date Time that the alert was sent')),
                ('description', models.CharField(help_text='description of the alert with metadata around triggered features', max_length=20)),
                ('alertContentLocation', models.CharField(help_text='a path to the content that trggered the alert for review', max_length=20)),
            ],
            options={
                'ordering': ['confidence', '-firedDateTime'],
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
