# Generated by Django 3.2.3 on 2021-05-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_auto_20210525_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
    ]
