# Generated by Django 3.2.3 on 2021-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_rename_alerts_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('cameraId', models.IntegerField(help_text='Unique ID for Camera', primary_key=True, serialize=False)),
                ('camGeoLoc', models.CharField(help_text='Geo location of the camera', max_length=30)),
                ('streamLoc', models.CharField(help_text='Location of the camera stream', max_length=30)),
                ('camName', models.CharField(help_text='Location of the camera stream', max_length=20)),
            ],
        ),
    ]
