# Generated by Django 3.2.3 on 2021-05-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_cameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the camera active'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='typeId',
            field=models.ForeignKey(help_text='foreign key for the type table', on_delete=django.db.models.deletion.CASCADE, to='cctv.type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='alertId',
            field=models.ForeignKey(help_text='foreign key for the alert table', on_delete=django.db.models.deletion.CASCADE, to='cctv.alert'),
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('recordingId', models.IntegerField(help_text='Unique ID for the recording', primary_key=True, serialize=False)),
                ('recordingDate', models.DateTimeField(help_text='Date time of the recording')),
                ('cameraId', models.ForeignKey(help_text='foreifn key for the camera table', on_delete=django.db.models.deletion.CASCADE, to='cctv.cameras')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='recordingId',
            field=models.ForeignKey(default=0, help_text='foreign key for the recording log', on_delete=django.db.models.deletion.CASCADE, to='cctv.recordings'),
        ),
    ]
